/*
 * Auto-generated by gen-sci-methods.py from sciwrappers.[ch]
 * Do not edit!
 */
GEANY_EXPORT
void 				scintilla_object_set_text				(ScintillaObject *sci,  const gchar *text) __attribute__((alias("sci_set_text")));
GEANY_EXPORT
gboolean			scintilla_object_has_selection			(ScintillaObject *sci) __attribute__((alias("sci_has_selection")));
GEANY_EXPORT
void 				scintilla_object_end_undo_action			(ScintillaObject *sci) __attribute__((alias("sci_end_undo_action")));
GEANY_EXPORT
void 				scintilla_object_start_undo_action		(ScintillaObject *sci) __attribute__((alias("sci_start_undo_action")));
GEANY_EXPORT
void				scintilla_object_set_marker_at_line		(ScintillaObject *sci, gint line_number, gint marker) __attribute__((alias("sci_set_marker_at_line")));
GEANY_EXPORT
void				scintilla_object_delete_marker_at_line	(ScintillaObject *sci, gint line_number, gint marker) __attribute__((alias("sci_delete_marker_at_line")));
GEANY_EXPORT
gboolean 			scintilla_object_is_marker_set_at_line	(ScintillaObject *sci, gint line, gint marker) __attribute__((alias("sci_is_marker_set_at_line")));
GEANY_EXPORT
gint 				scintilla_object_get_col_from_position	(ScintillaObject *sci, gint position) __attribute__((alias("sci_get_col_from_position")));
GEANY_EXPORT
gint 				scintilla_object_get_line_from_position	(ScintillaObject *sci, gint position) __attribute__((alias("sci_get_line_from_position")));
GEANY_EXPORT
gint 				scintilla_object_get_position_from_line	(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_position_from_line")));
GEANY_EXPORT
gint 				scintilla_object_get_current_position	(ScintillaObject *sci) __attribute__((alias("sci_get_current_position")));
GEANY_EXPORT
void 				scintilla_object_set_current_position	(ScintillaObject *sci, gint position, gboolean scroll_to_caret) __attribute__((alias("sci_set_current_position")));
GEANY_EXPORT
gint				scintilla_object_get_selection_start		(ScintillaObject *sci) __attribute__((alias("sci_get_selection_start")));
GEANY_EXPORT
gint				scintilla_object_get_selection_end		(ScintillaObject *sci) __attribute__((alias("sci_get_selection_end")));
GEANY_EXPORT
void 				scintilla_object_replace_sel				(ScintillaObject *sci, const gchar *text) __attribute__((alias("sci_replace_sel")));
GEANY_EXPORT
gint				scintilla_object_get_selection_mode		(ScintillaObject *sci) __attribute__((alias("sci_get_selection_mode")));
GEANY_EXPORT
void				scintilla_object_set_selection_mode		(ScintillaObject *sci, gint mode) __attribute__((alias("sci_set_selection_mode")));
GEANY_EXPORT
void 				scintilla_object_set_selection_start		(ScintillaObject *sci, gint position) __attribute__((alias("sci_set_selection_start")));
GEANY_EXPORT
void				scintilla_object_set_selection_end		(ScintillaObject *sci, gint position) __attribute__((alias("sci_set_selection_end")));
GEANY_EXPORT
gint				scintilla_object_get_length				(ScintillaObject *sci) __attribute__((alias("sci_get_length")));
GEANY_EXPORT
void				scintilla_object_get_text				(ScintillaObject *sci, gint len, gchar *text) __attribute__((alias("sci_get_text")));
GEANY_EXPORT
gchar*				scintilla_object_get_contents			(ScintillaObject *sci, gint buffer_len) __attribute__((alias("sci_get_contents")));
GEANY_EXPORT
void				scintilla_object_get_selected_text		(ScintillaObject *sci, gchar *text) __attribute__((alias("sci_get_selected_text")));
GEANY_EXPORT
gint				scintilla_object_get_selected_text_length(ScintillaObject *sci) __attribute__((alias("sci_get_selected_text_length")));
GEANY_EXPORT
gchar*				scintilla_object_get_selection_contents	(ScintillaObject *sci) __attribute__((alias("sci_get_selection_contents")));
GEANY_EXPORT
gchar*				scintilla_object_get_line				(ScintillaObject *sci, gint line_num) __attribute__((alias("sci_get_line")));
GEANY_EXPORT
gint 				scintilla_object_get_line_length			(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_line_length")));
GEANY_EXPORT
gint				scintilla_object_get_line_count			(ScintillaObject *sci) __attribute__((alias("sci_get_line_count")));
GEANY_EXPORT
gint				scintilla_object_get_line_end_position	(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_line_end_position")));
GEANY_EXPORT
gboolean			scintilla_object_get_line_is_visible		(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_line_is_visible")));
GEANY_EXPORT
void				scintilla_object_ensure_line_is_visible	(ScintillaObject *sci, gint line) __attribute__((alias("sci_ensure_line_is_visible")));
GEANY_EXPORT
gint				scintilla_object_get_tab_width			(ScintillaObject *sci) __attribute__((alias("sci_get_tab_width")));
GEANY_EXPORT
gchar				scintilla_object_get_char_at				(ScintillaObject *sci, gint pos) __attribute__((alias("sci_get_char_at")));
GEANY_EXPORT
void				scintilla_object_scroll_caret			(ScintillaObject *sci) __attribute__((alias("sci_scroll_caret")));
GEANY_EXPORT
void				scintilla_object_set_font				(ScintillaObject *sci, gint style, const gchar *font, gint size) __attribute__((alias("sci_set_font")));
GEANY_EXPORT
void				scintilla_object_goto_line				(ScintillaObject *sci, gint line, gboolean unfold) __attribute__((alias("sci_goto_line")));
GEANY_EXPORT
gint				scintilla_object_get_style_at			(ScintillaObject *sci, gint position) __attribute__((alias("sci_get_style_at")));
GEANY_EXPORT
gchar*				scintilla_object_get_contents_range		(ScintillaObject *sci, gint start, gint end) __attribute__((alias("sci_get_contents_range")));
GEANY_EXPORT
void				scintilla_object_insert_text				(ScintillaObject *sci, gint pos, const gchar *text) __attribute__((alias("sci_insert_text")));
GEANY_EXPORT
void				scintilla_object_set_target_start		(ScintillaObject *sci, gint start) __attribute__((alias("sci_set_target_start")));
GEANY_EXPORT
void				scintilla_object_set_target_end			(ScintillaObject *sci, gint end) __attribute__((alias("sci_set_target_end")));
GEANY_EXPORT
gint				scintilla_object_replace_target			(ScintillaObject *sci, const gchar *text, gboolean regex) __attribute__((alias("sci_replace_target")));
GEANY_EXPORT
gint				scintilla_object_get_lexer				(ScintillaObject *sci) __attribute__((alias("sci_get_lexer")));
GEANY_EXPORT
void				scintilla_object_send_command			(ScintillaObject *sci, gint cmd) __attribute__((alias("sci_send_command")));
GEANY_EXPORT
gint				scintilla_object_get_current_line		(ScintillaObject *sci) __attribute__((alias("sci_get_current_line")));
GEANY_EXPORT
void				scintilla_object_indicator_set			(ScintillaObject *sci, gint indic) __attribute__((alias("sci_indicator_set")));
GEANY_EXPORT
void				scintilla_object_indicator_clear			(ScintillaObject *sci, gint pos, gint len) __attribute__((alias("sci_indicator_clear")));
GEANY_EXPORT
void				scintilla_object_set_line_indentation	(ScintillaObject *sci, gint line, gint indent) __attribute__((alias("sci_set_line_indentation")));
GEANY_EXPORT
gint				scintilla_object_get_line_indentation	(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_line_indentation")));
GEANY_EXPORT
gint				scintilla_object_find_matching_brace		(ScintillaObject *sci, gint pos) __attribute__((alias("sci_find_matching_brace")));
#ifndef G_IR_SCANNER
GEANY_EXPORT
gint				scintilla_object_find_text				(ScintillaObject *sci, gint flags, struct Sci_TextToFind *ttf) __attribute__((alias("sci_find_text")));
gchar*				scintilla_object_get_string				(ScintillaObject *sci, guint msg, gulong wParam) __attribute__((alias("sci_get_string")));
GEANY_EXPORT
void				scintilla_object_get_text_range			(ScintillaObject *sci, gint start, gint end, gchar *text) __attribute__((alias("sci_get_text_range")));
void 				scintilla_object_set_line_numbers		(ScintillaObject *sci,  gboolean set) __attribute__((alias("sci_set_line_numbers")));
void				scintilla_object_set_mark_long_lines		(ScintillaObject *sci,	gint type, gint column, const gchar *color) __attribute__((alias("sci_set_mark_long_lines")));
void 				scintilla_object_add_text				(ScintillaObject *sci,  const gchar *text) __attribute__((alias("sci_add_text")));
gboolean			scintilla_object_can_redo				(ScintillaObject *sci) __attribute__((alias("sci_can_redo")));
gboolean			scintilla_object_can_undo				(ScintillaObject *sci) __attribute__((alias("sci_can_undo")));
void 				scintilla_object_undo					(ScintillaObject *sci) __attribute__((alias("sci_undo")));
void 				scintilla_object_redo					(ScintillaObject *sci) __attribute__((alias("sci_redo")));
void 				scintilla_object_empty_undo_buffer		(ScintillaObject *sci) __attribute__((alias("sci_empty_undo_buffer")));
gboolean			scintilla_object_is_modified				(ScintillaObject *sci) __attribute__((alias("sci_is_modified")));
void				scintilla_object_set_visible_eols		(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_visible_eols")));
void				scintilla_object_set_lines_wrapped		(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_lines_wrapped")));
void				scintilla_object_set_visible_white_spaces(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_visible_white_spaces")));
void 				scintilla_object_convert_eols			(ScintillaObject *sci, gint eolmode) __attribute__((alias("sci_convert_eols")));
gint				scintilla_object_get_eol_mode			(ScintillaObject *sci) __attribute__((alias("sci_get_eol_mode")));
void 				scintilla_object_set_eol_mode			(ScintillaObject *sci, gint eolmode) __attribute__((alias("sci_set_eol_mode")));
void 				scintilla_object_zoom_in					(ScintillaObject *sci) __attribute__((alias("sci_zoom_in")));
void 				scintilla_object_zoom_out				(ScintillaObject *sci) __attribute__((alias("sci_zoom_out")));
void 				scintilla_object_zoom_off				(ScintillaObject *sci) __attribute__((alias("sci_zoom_off")));
void				scintilla_object_toggle_marker_at_line	(ScintillaObject *sci, gint line, gint marker) __attribute__((alias("sci_toggle_marker_at_line")));
gint				scintilla_object_marker_next				(ScintillaObject *sci, gint line, gint marker_mask, gboolean wrap) __attribute__((alias("sci_marker_next")));
gint				scintilla_object_marker_previous			(ScintillaObject *sci, gint line, gint marker_mask, gboolean wrap) __attribute__((alias("sci_marker_previous")));
gint 				scintilla_object_get_position_from_col (ScintillaObject *sci, gint line, gint col) __attribute__((alias("sci_get_position_from_col")));
void 				scintilla_object_set_current_line		(ScintillaObject *sci, gint line) __attribute__((alias("sci_set_current_line")));
void 				scintilla_object_cut						(ScintillaObject *sci) __attribute__((alias("sci_cut")));
void 				scintilla_object_copy					(ScintillaObject *sci) __attribute__((alias("sci_copy")));
void 				scintilla_object_paste					(ScintillaObject *sci) __attribute__((alias("sci_paste")));
void 				scintilla_object_clear					(ScintillaObject *sci) __attribute__((alias("sci_clear")));
gint				scintilla_object_get_pos_at_line_sel_start(ScintillaObject*sci, gint line) __attribute__((alias("sci_get_pos_at_line_sel_start")));
gint				scintilla_object_get_pos_at_line_sel_end	(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_pos_at_line_sel_end")));
void				scintilla_object_set_selection			(ScintillaObject *sci, gint anchorPos, gint currentPos) __attribute__((alias("sci_set_selection")));
gint				scintilla_object_get_position_from_xy	(ScintillaObject *sci, gint x, gint y, gboolean nearby) __attribute__((alias("sci_get_position_from_xy")));
void 				scintilla_object_set_undo_collection		(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_undo_collection")));
void 				scintilla_object_toggle_fold				(ScintillaObject *sci, gint line) __attribute__((alias("sci_toggle_fold")));
gint				scintilla_object_get_fold_level			(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_fold_level")));
gint				scintilla_object_get_fold_parent			(ScintillaObject *sci, gint start_line) __attribute__((alias("sci_get_fold_parent")));
void 				scintilla_object_set_folding_margin_visible (ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_folding_margin_visible")));
gboolean			scintilla_object_get_fold_expanded		(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_fold_expanded")));
void				scintilla_object_colourise				(ScintillaObject *sci, gint start, gint end) __attribute__((alias("sci_colourise")));
void				scintilla_object_clear_all				(ScintillaObject *sci) __attribute__((alias("sci_clear_all")));
gint				scintilla_object_get_end_styled			(ScintillaObject *sci) __attribute__((alias("sci_get_end_styled")));
void				scintilla_object_set_tab_width			(ScintillaObject *sci, gint width) __attribute__((alias("sci_set_tab_width")));
void				scintilla_object_set_savepoint			(ScintillaObject *sci) __attribute__((alias("sci_set_savepoint")));
void				scintilla_object_set_indentation_guides	(ScintillaObject *sci, gint mode) __attribute__((alias("sci_set_indentation_guides")));
void				scintilla_object_use_popup				(ScintillaObject *sci, gboolean enable) __attribute__((alias("sci_use_popup")));
void				scintilla_object_goto_pos				(ScintillaObject *sci, gint pos, gboolean unfold) __attribute__((alias("sci_goto_pos")));
void				scintilla_object_set_search_anchor		(ScintillaObject *sci) __attribute__((alias("sci_set_search_anchor")));
void				scintilla_object_set_anchor				(ScintillaObject *sci, gint pos) __attribute__((alias("sci_set_anchor")));
void				scintilla_object_scroll_lines			(ScintillaObject *sci, gint lines) __attribute__((alias("sci_scroll_lines")));
void				scintilla_object_scroll_columns			(ScintillaObject *sci, gint columns) __attribute__((alias("sci_scroll_columns")));
gint				scintilla_object_search_next				(ScintillaObject *sci, gint flags, const gchar *text) __attribute__((alias("sci_search_next")));
gint				scintilla_object_search_prev				(ScintillaObject *sci, gint flags, const gchar *text) __attribute__((alias("sci_search_prev")));
void				scintilla_object_marker_delete_all		(ScintillaObject *sci, gint marker) __attribute__((alias("sci_marker_delete_all")));
void				scintilla_object_set_symbol_margin		(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_symbol_margin")));
void				scintilla_object_set_codepage			(ScintillaObject *sci, gint cp) __attribute__((alias("sci_set_codepage")));
void				scintilla_object_clear_cmdkey			(ScintillaObject *sci, gint key) __attribute__((alias("sci_clear_cmdkey")));
void				scintilla_object_assign_cmdkey			(ScintillaObject *sci, gint key, gint command) __attribute__((alias("sci_assign_cmdkey")));
void				scintilla_object_selection_duplicate		(ScintillaObject *sci) __attribute__((alias("sci_selection_duplicate")));
void				scintilla_object_line_duplicate			(ScintillaObject *sci) __attribute__((alias("sci_line_duplicate")));
void				scintilla_object_target_from_selection	(ScintillaObject *sci) __attribute__((alias("sci_target_from_selection")));
gint				scintilla_object_get_target_end			(ScintillaObject *sci) __attribute__((alias("sci_get_target_end")));
void				scintilla_object_set_keywords			(ScintillaObject *sci, guint k, const gchar *text) __attribute__((alias("sci_set_keywords")));
void				scintilla_object_set_lexer				(ScintillaObject *sci, guint lexer_id) __attribute__((alias("sci_set_lexer")));
void				scintilla_object_set_readonly			(ScintillaObject *sci, gboolean readonly) __attribute__((alias("sci_set_readonly")));
gint				scintilla_object_get_zoom				(ScintillaObject *sci) __attribute__((alias("sci_get_zoom")));
gint				scintilla_object_get_lines_selected		(ScintillaObject *sci) __attribute__((alias("sci_get_lines_selected")));
gint				scintilla_object_get_first_visible_line	(ScintillaObject *sci) __attribute__((alias("sci_get_first_visible_line")));
void				scintilla_object_indicator_fill			(ScintillaObject *sci, gint pos, gint len) __attribute__((alias("sci_indicator_fill")));
void				scintilla_object_select_all				(ScintillaObject *sci) __attribute__((alias("sci_select_all")));
gint				scintilla_object_get_line_indent_position(ScintillaObject *sci, gint line) __attribute__((alias("sci_get_line_indent_position")));
void				scintilla_object_set_autoc_max_height	(ScintillaObject *sci, gint val) __attribute__((alias("sci_set_autoc_max_height")));
gint				scintilla_object_get_overtype			(ScintillaObject *sci) __attribute__((alias("sci_get_overtype")));
void				scintilla_object_set_tab_indents			(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_tab_indents")));
void				scintilla_object_set_use_tabs			(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_use_tabs")));
void				scintilla_object_set_scrollbar_mode		(ScintillaObject *sci, gboolean visible) __attribute__((alias("sci_set_scrollbar_mode")));
void				scintilla_object_set_caret_policy_x		(ScintillaObject *sci, gint policy, gint slop) __attribute__((alias("sci_set_caret_policy_x")));
void				scintilla_object_set_caret_policy_y		(ScintillaObject *sci, gint policy, gint slop) __attribute__((alias("sci_set_caret_policy_y")));
void				scintilla_object_set_scroll_stop_at_last_line	(ScintillaObject *sci, gboolean set) __attribute__((alias("sci_set_scroll_stop_at_last_line")));
void				scintilla_object_cancel					(ScintillaObject *sci) __attribute__((alias("sci_cancel")));
gint				scintilla_object_get_position_after		(ScintillaObject *sci, gint start) __attribute__((alias("sci_get_position_after")));
gint				scintilla_object_word_start_position		(ScintillaObject *sci, gint position, gboolean onlyWordCharacters) __attribute__((alias("sci_word_start_position")));
gint				scintilla_object_word_end_position		(ScintillaObject *sci, gint position, gboolean onlyWordCharacters) __attribute__((alias("sci_word_end_position")));
void				scintilla_object_lines_join				(ScintillaObject *sci) __attribute__((alias("sci_lines_join")));
gint				scintilla_object_text_width				(ScintillaObject *sci, gint styleNumber, const gchar *text) __attribute__((alias("sci_text_width")));
void				scintilla_object_move_selected_lines_down    (ScintillaObject *sci) __attribute__((alias("sci_move_selected_lines_down")));
void				scintilla_object_move_selected_lines_up      (ScintillaObject *sci) __attribute__((alias("sci_move_selected_lines_up")));
#endif /* G_IR_SCANNER */
