/* document.c generated by valac 0.24.0, the Vala compiler
 * generated from document.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "geanyapi.h"
#include <document.h>
#include <geanyobject.h>
#include <stdlib.h>
#include <string.h>
#include <editor.h>
#include <ScintillaWidget.h>
#include <Scintilla.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GeanyGObjectDocumentPrivate {
	struct GeanyDocument* _doc;
	gboolean owns_doc;
};


static gpointer geany_gobject_document_parent_class = NULL;

#define GEANY_GOBJECT_DOCUMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_GOBJECT_TYPE_DOCUMENT, GeanyGObjectDocumentPrivate))
enum  {
	GEANY_GOBJECT_DOCUMENT_DUMMY_PROPERTY,
	GEANY_GOBJECT_DOCUMENT_IS_READONLY,
	GEANY_GOBJECT_DOCUMENT_CHANGED,
	GEANY_GOBJECT_DOCUMENT_IS_VALID,
	GEANY_GOBJECT_DOCUMENT_HAS_BOM,
	GEANY_GOBJECT_DOCUMENT_HAS_TAGS,
	GEANY_GOBJECT_DOCUMENT_INDEX,
	GEANY_GOBJECT_DOCUMENT_DISPLAY_NAME,
	GEANY_GOBJECT_DOCUMENT_ENCODING
};
static GeanyGObjectDocument* geany_gobject_document_new (void);
static GeanyGObjectDocument* geany_gobject_document_construct (GType object_type);
static void __lambda3_ (GeanyGObjectDocument* self, struct GeanyDocument* doc);
static void ___lambda3__geany_raw_object_document_close (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self);
static void __lambda4_ (GeanyGObjectDocument* self, struct GeanyDocument* doc);
static void ___lambda4__geany_raw_object_document_activate (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self);
static void __lambda5_ (GeanyGObjectDocument* self, struct GeanyDocument* doc);
static void ___lambda5__geany_raw_object_document_reload (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self);
static void __lambda6_ (GeanyGObjectDocument* self, struct GeanyDocument* doc);
static void ___lambda6__geany_raw_object_document_before_save (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self);
static void __lambda7_ (GeanyGObjectDocument* self, struct GeanyDocument* doc);
static void ___lambda7__geany_raw_object_document_save (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self);
static void geany_gobject_document_finalize (GObject* obj);
static void _vala_geany_gobject_document_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_geany_gobject_document_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void __lambda3_ (GeanyGObjectDocument* self, struct GeanyDocument* doc) {
	struct GeanyDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	g_return_if_fail (doc != NULL);
	_tmp0_ = doc;
	_tmp1_ = self->priv->_doc;
	if (_tmp0_ == _tmp1_) {
		g_signal_emit_by_name (self, "closed");
	}
}


static void ___lambda3__geany_raw_object_document_close (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self) {
	__lambda3_ ((GeanyGObjectDocument*) self, doc);
}


static void __lambda4_ (GeanyGObjectDocument* self, struct GeanyDocument* doc) {
	struct GeanyDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	g_return_if_fail (doc != NULL);
	_tmp0_ = doc;
	_tmp1_ = self->priv->_doc;
	if (_tmp0_ == _tmp1_) {
		g_signal_emit_by_name (self, "activate");
	}
}


static void ___lambda4__geany_raw_object_document_activate (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self) {
	__lambda4_ ((GeanyGObjectDocument*) self, doc);
}


static void __lambda5_ (GeanyGObjectDocument* self, struct GeanyDocument* doc) {
	struct GeanyDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	g_return_if_fail (doc != NULL);
	_tmp0_ = doc;
	_tmp1_ = self->priv->_doc;
	if (_tmp0_ == _tmp1_) {
		g_signal_emit_by_name (self, "reloaded");
	}
}


static void ___lambda5__geany_raw_object_document_reload (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self) {
	__lambda5_ ((GeanyGObjectDocument*) self, doc);
}


static void __lambda6_ (GeanyGObjectDocument* self, struct GeanyDocument* doc) {
	struct GeanyDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	g_return_if_fail (doc != NULL);
	_tmp0_ = doc;
	_tmp1_ = self->priv->_doc;
	if (_tmp0_ == _tmp1_) {
		g_signal_emit_by_name (self, "before-save");
	}
}


static void ___lambda6__geany_raw_object_document_before_save (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self) {
	__lambda6_ ((GeanyGObjectDocument*) self, doc);
}


static void __lambda7_ (GeanyGObjectDocument* self, struct GeanyDocument* doc) {
	struct GeanyDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	g_return_if_fail (doc != NULL);
	_tmp0_ = doc;
	_tmp1_ = self->priv->_doc;
	if (_tmp0_ == _tmp1_) {
		g_signal_emit_by_name (self, "saved");
	}
}


static void ___lambda7__geany_raw_object_document_save (GeanyObject* _sender, struct GeanyDocument* doc, gpointer self) {
	__lambda7_ ((GeanyGObjectDocument*) self, doc);
}


static GeanyGObjectDocument* geany_gobject_document_construct (GType object_type) {
	GeanyGObjectDocument * self = NULL;
	GeanyObject* _tmp0_ = NULL;
	GeanyObject* _tmp1_ = NULL;
	GeanyObject* _tmp2_ = NULL;
	GeanyObject* _tmp3_ = NULL;
	GeanyObject* _tmp4_ = NULL;
	self = (GeanyGObjectDocument*) g_object_new (object_type, NULL);
	_tmp0_ = geany_object;
	g_signal_connect_object (_tmp0_, "document-close", (GCallback) ___lambda3__geany_raw_object_document_close, self, 0);
	_tmp1_ = geany_object;
	g_signal_connect_object (_tmp1_, "document-activate", (GCallback) ___lambda4__geany_raw_object_document_activate, self, 0);
	_tmp2_ = geany_object;
	g_signal_connect_object (_tmp2_, "document-reload", (GCallback) ___lambda5__geany_raw_object_document_reload, self, 0);
	_tmp3_ = geany_object;
	g_signal_connect_object (_tmp3_, "document-before-save", (GCallback) ___lambda6__geany_raw_object_document_before_save, self, 0);
	_tmp4_ = geany_object;
	g_signal_connect_object (_tmp4_, "document-save", (GCallback) ___lambda7__geany_raw_object_document_save, self, 0);
	return self;
}


static GeanyGObjectDocument* geany_gobject_document_new (void) {
	return geany_gobject_document_construct (GEANY_GOBJECT_TYPE_DOCUMENT);
}


GeanyGObjectDocument* geany_gobject_document_construct_new_file (GType object_type, const gchar* utf8_filename, const gchar* text) {
	GeanyGObjectDocument * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	struct GeanyDocument* _tmp2_ = NULL;
	self = (GeanyGObjectDocument*) geany_gobject_document_construct (object_type);
	_tmp0_ = utf8_filename;
	_tmp1_ = text;
	_tmp2_ = document_new_file (_tmp0_, NULL, _tmp1_);
	self->priv->_doc = _tmp2_;
	self->priv->owns_doc = TRUE;
	return self;
}


GeanyGObjectDocument* geany_gobject_document_new_new_file (const gchar* utf8_filename, const gchar* text) {
	return geany_gobject_document_construct_new_file (GEANY_GOBJECT_TYPE_DOCUMENT, utf8_filename, text);
}


GeanyGObjectDocument* geany_gobject_document_construct_from_file (GType object_type, const gchar* locale_filename, gboolean readonly, const gchar* forced_enc) {
	GeanyGObjectDocument * self = NULL;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_ = NULL;
	struct GeanyDocument* _tmp3_ = NULL;
	g_return_val_if_fail (locale_filename != NULL, NULL);
	self = (GeanyGObjectDocument*) geany_gobject_document_construct (object_type);
	_tmp0_ = locale_filename;
	_tmp1_ = readonly;
	_tmp2_ = forced_enc;
	_tmp3_ = document_open_file (_tmp0_, _tmp1_, NULL, _tmp2_);
	self->priv->_doc = _tmp3_;
	self->priv->owns_doc = TRUE;
	return self;
}


GeanyGObjectDocument* geany_gobject_document_new_from_file (const gchar* locale_filename, gboolean readonly, const gchar* forced_enc) {
	return geany_gobject_document_construct_from_file (GEANY_GOBJECT_TYPE_DOCUMENT, locale_filename, readonly, forced_enc);
}


GeanyGObjectDocument* geany_gobject_document_get_current (void) {
	GeanyGObjectDocument* result = NULL;
	GeanyGObjectDocument* obj = NULL;
	GeanyGObjectDocument* _tmp0_ = NULL;
	struct GeanyDocument* _tmp1_ = NULL;
	_tmp0_ = geany_gobject_document_new ();
	obj = _tmp0_;
	_tmp1_ = document_get_current ();
	obj->priv->_doc = _tmp1_;
	obj->priv->owns_doc = FALSE;
	result = obj;
	return result;
}


gboolean geany_gobject_document_close (GeanyGObjectDocument* self) {
	gboolean result = FALSE;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = document_close (_tmp0_);
	result = _tmp1_;
	return result;
}


gboolean geany_gobject_document_save (GeanyGObjectDocument* self, gboolean force) {
	gboolean result = FALSE;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = force;
	_tmp2_ = document_save_file (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


gboolean geany_gobject_document_save_as (GeanyGObjectDocument* self, const gchar* file_name) {
	gboolean result = FALSE;
	struct GeanyDocument* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = file_name;
	_tmp2_ = document_save_file_as (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


gboolean geany_gobject_document_reload (GeanyGObjectDocument* self, const gchar* forced_enc) {
	gboolean result = FALSE;
	struct GeanyDocument* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = forced_enc;
	_tmp2_ = document_reload_file (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


gboolean geany_gobject_document_get_is_readonly (GeanyGObjectDocument* self) {
	gboolean result;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->readonly;
	result = _tmp1_;
	return result;
}


void geany_gobject_document_set_is_readonly (GeanyGObjectDocument* self, gboolean value) {
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	struct GeanyDocument* _tmp2_ = NULL;
	struct GeanyEditor* _tmp3_ = NULL;
	ScintillaObject* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	struct GeanyDocument* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp1_ = value;
	if (_tmp1_) {
		_tmp0_ = 1;
	} else {
		_tmp0_ = 0;
	}
	_tmp2_ = self->priv->_doc;
	_tmp3_ = _tmp2_->editor;
	_tmp4_ = _tmp3_->sci;
	_tmp5_ = SCI_SETREADONLY;
	scintilla_send_message (_tmp4_, (guint) _tmp5_, (gulong) _tmp0_, (gulong) 0);
	_tmp6_ = self->priv->_doc;
	_tmp7_ = value;
	_tmp6_->readonly = _tmp7_;
	g_object_notify ((GObject *) self, "is-readonly");
}


gboolean geany_gobject_document_get_changed (GeanyGObjectDocument* self) {
	gboolean result;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->changed;
	result = _tmp1_;
	return result;
}


void geany_gobject_document_set_changed (GeanyGObjectDocument* self, gboolean value) {
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = value;
	document_set_text_changed (_tmp0_, _tmp1_);
	g_object_notify ((GObject *) self, "changed");
}


gboolean geany_gobject_document_get_is_valid (GeanyGObjectDocument* self) {
	gboolean result;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->is_valid;
	result = _tmp1_;
	return result;
}


gboolean geany_gobject_document_get_has_bom (GeanyGObjectDocument* self) {
	gboolean result;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->has_bom;
	result = _tmp1_;
	return result;
}


gboolean geany_gobject_document_get_has_tags (GeanyGObjectDocument* self) {
	gboolean result;
	struct GeanyDocument* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->has_tags;
	result = _tmp1_;
	return result;
}


gint geany_gobject_document_get_index (GeanyGObjectDocument* self) {
	gint result;
	struct GeanyDocument* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->index;
	result = _tmp1_;
	return result;
}


gchar* geany_gobject_document_get_display_name (GeanyGObjectDocument* self) {
	gchar* result;
	struct GeanyDocument* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = document_get_basename_for_display (_tmp0_, -1);
	result = _tmp1_;
	return result;
}


const gchar* geany_gobject_document_get_encoding (GeanyGObjectDocument* self) {
	const gchar* result;
	struct GeanyDocument* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = _tmp0_->encoding;
	result = _tmp1_;
	return result;
}


void geany_gobject_document_set_encoding (GeanyGObjectDocument* self, const gchar* value) {
	struct GeanyDocument* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_doc;
	_tmp1_ = value;
	document_set_encoding (_tmp0_, _tmp1_);
	g_object_notify ((GObject *) self, "encoding");
}


static void geany_gobject_document_class_init (GeanyGObjectDocumentClass * klass) {
	geany_gobject_document_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyGObjectDocumentPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_geany_gobject_document_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_geany_gobject_document_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_gobject_document_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_IS_READONLY, g_param_spec_boolean ("is-readonly", "is-readonly", "is-readonly", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_CHANGED, g_param_spec_boolean ("changed", "changed", "changed", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_IS_VALID, g_param_spec_boolean ("is-valid", "is-valid", "is-valid", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_HAS_BOM, g_param_spec_boolean ("has-bom", "has-bom", "has-bom", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_HAS_TAGS, g_param_spec_boolean ("has-tags", "has-tags", "has-tags", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_INDEX, g_param_spec_int ("index", "index", "index", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_DISPLAY_NAME, g_param_spec_string ("display-name", "display-name", "display-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_GOBJECT_DOCUMENT_ENCODING, g_param_spec_string ("encoding", "encoding", "encoding", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("closed", GEANY_GOBJECT_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("reloaded", GEANY_GOBJECT_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("before_save", GEANY_GOBJECT_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("saved", GEANY_GOBJECT_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("activate", GEANY_GOBJECT_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void geany_gobject_document_instance_init (GeanyGObjectDocument * self) {
	self->priv = GEANY_GOBJECT_DOCUMENT_GET_PRIVATE (self);
}


static void geany_gobject_document_finalize (GObject* obj) {
	GeanyGObjectDocument * self;
	gboolean _tmp0_ = FALSE;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEANY_GOBJECT_TYPE_DOCUMENT, GeanyGObjectDocument);
	_tmp0_ = self->priv->owns_doc;
	if (_tmp0_) {
		gboolean _tmp1_ = FALSE;
		_tmp1_ = geany_gobject_document_close (self);
		if (!_tmp1_) {
			geany_gobject_document_set_changed (self, FALSE);
			geany_gobject_document_close (self);
		}
	}
	G_OBJECT_CLASS (geany_gobject_document_parent_class)->finalize (obj);
}


GType geany_gobject_document_get_type (void) {
	static volatile gsize geany_gobject_document_type_id__volatile = 0;
	if (g_once_init_enter (&geany_gobject_document_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyGObjectDocumentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_gobject_document_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyGObjectDocument), 0, (GInstanceInitFunc) geany_gobject_document_instance_init, NULL };
		GType geany_gobject_document_type_id;
		geany_gobject_document_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyGObjectDocument", &g_define_type_info, 0);
		g_once_init_leave (&geany_gobject_document_type_id__volatile, geany_gobject_document_type_id);
	}
	return geany_gobject_document_type_id__volatile;
}


static void _vala_geany_gobject_document_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyGObjectDocument * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEANY_GOBJECT_TYPE_DOCUMENT, GeanyGObjectDocument);
	switch (property_id) {
		case GEANY_GOBJECT_DOCUMENT_IS_READONLY:
		g_value_set_boolean (value, geany_gobject_document_get_is_readonly (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_CHANGED:
		g_value_set_boolean (value, geany_gobject_document_get_changed (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_IS_VALID:
		g_value_set_boolean (value, geany_gobject_document_get_is_valid (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_HAS_BOM:
		g_value_set_boolean (value, geany_gobject_document_get_has_bom (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_HAS_TAGS:
		g_value_set_boolean (value, geany_gobject_document_get_has_tags (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_INDEX:
		g_value_set_int (value, geany_gobject_document_get_index (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_DISPLAY_NAME:
		g_value_take_string (value, geany_gobject_document_get_display_name (self));
		break;
		case GEANY_GOBJECT_DOCUMENT_ENCODING:
		g_value_set_string (value, geany_gobject_document_get_encoding (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_geany_gobject_document_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyGObjectDocument * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEANY_GOBJECT_TYPE_DOCUMENT, GeanyGObjectDocument);
	switch (property_id) {
		case GEANY_GOBJECT_DOCUMENT_IS_READONLY:
		geany_gobject_document_set_is_readonly (self, g_value_get_boolean (value));
		break;
		case GEANY_GOBJECT_DOCUMENT_CHANGED:
		geany_gobject_document_set_changed (self, g_value_get_boolean (value));
		break;
		case GEANY_GOBJECT_DOCUMENT_ENCODING:
		geany_gobject_document_set_encoding (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



