/* view.c generated by valac 0.20.1, the Vala compiler
 * generated from view.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "geanyapi.h"
#include <editor.h>


struct _GeanyViewPrivate {
	struct GeanyEditor* ed;
};


static gpointer geany_view_parent_class = NULL;

#define GEANY_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_TYPE_VIEW, GeanyViewPrivate))
enum  {
	GEANY_VIEW_DUMMY_PROPERTY
};
GeanyView* geany_view_new (struct GeanyEditor* editor);
GeanyView* geany_view_construct (GType object_type, struct GeanyEditor* editor);
static void geany_view_finalize (GObject* obj);


GeanyView* geany_view_construct (GType object_type, struct GeanyEditor* editor) {
	GeanyView * self = NULL;
	struct GeanyEditor* _tmp0_;
	g_return_val_if_fail (editor != NULL, NULL);
	self = (GeanyView*) g_object_new (object_type, NULL);
	_tmp0_ = editor;
	self->priv->ed = _tmp0_;
	return self;
}


GeanyView* geany_view_new (struct GeanyEditor* editor) {
	return geany_view_construct (GEANY_TYPE_VIEW, editor);
}


static void geany_view_class_init (GeanyViewClass * klass) {
	geany_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = geany_view_finalize;
}


static void geany_view_instance_init (GeanyView * self) {
	self->priv = GEANY_VIEW_GET_PRIVATE (self);
}


static void geany_view_finalize (GObject* obj) {
	GeanyView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEANY_TYPE_VIEW, GeanyView);
	G_OBJECT_CLASS (geany_view_parent_class)->finalize (obj);
}


GType geany_view_get_type (void) {
	static volatile gsize geany_view_type_id__volatile = 0;
	if (g_once_init_enter (&geany_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyView), 0, (GInstanceInitFunc) geany_view_instance_init, NULL };
		GType geany_view_type_id;
		geany_view_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyView", &g_define_type_info, 0);
		g_once_init_leave (&geany_view_type_id__volatile, geany_view_type_id);
	}
	return geany_view_type_id__volatile;
}



