name: C/C++ CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      GTK3: yes
      BINRELOC: no
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo python3 -m pip install meson ninja
        sudo apt-get install -y intltool libtool
        test -n "$MINGW" || sudo apt-get install -y libgtk-3-dev
        test -z "$MINGW" || sudo apt-get install -y mingw-w64-tools g++-mingw-w64-i686 gcc-mingw-w64-i686 binutils-mingw-w64-i686
        # fix broken pkg-config-crosswrapper, see https://bugs.launchpad.net/ubuntu/+source/mingw-w64/+bug/1327242
        test -z "$MINGW" || sudo sed -e 's/PKG_CONFIG_PATH=/&$PKG_CONFIG_PATH:/' -i /usr/bin/i686-w64-mingw32-pkg-config
        sudo apt-get install -y python-docutils rst2pdf
        # try not to install doxygen-latex because we don't need it and it's huge
        sudo apt-get install -y --no-install-recommends doxygen
        sudo apt-get install -y python-lxml
    - run: meson builddir
    - run: ninja -C builddir -v
    - run: ninja -C builddir test

  macos:
    runs-on: macos-latest
    env:
      GTK3: yes
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew install meson doxygen gtk+3 libtool intltool docutils
    - run: meson builddir
    - run: ninja -C builddir -v
    - run: ninja -C builddir test
