/* geanypluginlegacy.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __GEANYPLUGINLEGACY_H__
#define __GEANYPLUGINLEGACY_H__

#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <geanyplugin2.h>
#include <gmodule.h>

G_BEGIN_DECLS


#define GEANY_TYPE_PLUGIN_LEGACY (geany_plugin_legacy_get_type ())
#define GEANY_PLUGIN_LEGACY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_TYPE_PLUGIN_LEGACY, GeanyPluginLegacy))
#define GEANY_PLUGIN_LEGACY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_TYPE_PLUGIN_LEGACY, GeanyPluginLegacyClass))
#define GEANY_IS_PLUGIN_LEGACY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_TYPE_PLUGIN_LEGACY))
#define GEANY_IS_PLUGIN_LEGACY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_TYPE_PLUGIN_LEGACY))
#define GEANY_PLUGIN_LEGACY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_TYPE_PLUGIN_LEGACY, GeanyPluginLegacyClass))

typedef struct _GeanyPluginLegacy GeanyPluginLegacy;
typedef struct _GeanyPluginLegacyClass GeanyPluginLegacyClass;
typedef struct _GeanyPluginLegacyPrivate GeanyPluginLegacyPrivate;

typedef void (*GeanyDelegateInit) (void* geanydata);
typedef gint (*GeanyDelegateVersionCheck) (gint abi);
typedef GtkWidget* (*GeanyDelegateConfigure) (GtkDialog* parent);
typedef void (*GeanyDelegateConfigureSingle) (GtkWidget* parent);
typedef void (*GeanyDelegateHelp) ();
typedef void (*GeanyDelegateCleanup) ();
struct _GeanyPluginLegacy {
	GObject parent_instance;
	GeanyPluginLegacyPrivate * priv;
	GeanyDelegateInit _init;
	GeanyDelegateVersionCheck _version_check;
	GeanyDelegateConfigure _configure;
	GeanyDelegateConfigureSingle _configure_single;
	GeanyDelegateHelp _help;
	GeanyDelegateCleanup _cleanup;
	GModule* module;
};

struct _GeanyPluginLegacyClass {
	GObjectClass parent_class;
};


GType geany_plugin_legacy_get_type (void) G_GNUC_CONST;
GeanyPluginLegacy* geany_plugin_legacy_new (void);
GeanyPluginLegacy* geany_plugin_legacy_construct (GType object_type);


G_END_DECLS

#endif
